### ISSUE TITLE
Repo needed for releasing

### ISSUE THREAD

**Issue by bit-pirate** [ros-drivers/openni_tracker#4]
Shall we use https://github.com/ros-gbp? If yes, could someone add me to the organisation or create a repo there and give me push&pull rights (e.g. @jack-oquin). Thanks!

Otherwise, I'll create one on my private account.

**Comment by chadrockey** [comment]
https://github.com/ros-gbp/openni_tracker-release

**Comment by bit-pirate** [comment]
Thanks, Chad!

**Comment by jack-oquin** [comment]
There is also a ros-drivers-gbp available.

**Comment by bit-pirate** [comment]
I'm happy with ros-gdp. But if it is important, then I can move over to ros-drivers-gbp with a new release.

**Comment by jack-oquin** [comment]
Not worth the hassle of moving it.

Just wanted you to know that there is a release organization specifically
for ros-drivers. Many drivers were released via ros-gbp before
ros-drivers-gbp was created. It's not a problem.
